package dts

import (
	"fmt"
	"os"

	"github.com/urfave/cli/v2"

	"github.com/tarampampam/poke/internal/version"
)

// NewCommand creates `dts` command.
func NewCommand(content string) *cli.Command {
	var header = "// Code generated by the poke tool version v" + version.Version() + ". DO NOT EDIT.\n\n"

	return &cli.Command{
		Name:  "d.ts",
		Usage: "Print the 'common.d.ts' file",
		Action: func(c *cli.Context) (err error) {
			_, err = fmt.Fprint(os.Stdout, header, content)

			return
		},
	}
}
