# Docker-compose file is used only for local development. This is not production-ready example
version: '3.8'

volumes:
  tmp-data: {}
  golint-go: {}
  golint-cache: {}

services:
  go:
    build:
      target: builder
      args: [DEV_MODE=true]
    working_dir: /src
    environment:
      PS1: '\[\033[1;32m\]\[\033[1;36m\][\u@go] \[\033[1;34m\]\w\[\033[0;35m\] \[\033[1;36m\]# \[\033[0m\]'
      HOME: /tmp
      GOPATH: /tmp
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - tmp-data:/tmp:rw
      - .:/src:rw

  golint:
    image: golangci/golangci-lint:v1.50-alpine # Image page: <https://hub.docker.com/r/golangci/golangci-lint>
    environment:
      GOLANGCI_LINT_CACHE: /tmp/golint # <https://github.com/golangci/golangci-lint/blob/v1.33.0/internal/cache/default.go#L68>
    volumes:
      - golint-go:/go:rw # go dependencies will be downloaded on each run without this
      - golint-cache:/tmp/golint:rw
      - .:/src:ro
    working_dir: /src

  hugo:
    image: klakegg/hugo:0.107.0-ext-alpine
    volumes:
      - ./docs:/src:rw
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    working_dir: /src
    entrypoint: []
