disableAliases: true
disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: false
enableRobotsTXT: true
paginate: 7
rssLimit: 10

# Multilingual
defaultContentLanguage: en
#disableLanguages: []

outputs:
  home:
    - HTML
    - RSS
  section:
    - HTML
    - RSS
    - SITEMAP

outputFormats:
  SITEMAP: # add output format for section sitemap.xml
    mediaType: application/xml
    baseName: sitemap
    isHTML: false
    isPlainText: true
    noUgly: true
    rel: sitemap

caches:
  getjson:
    dir: ':cacheDir/:project'
    maxAge: 10s

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

taxonomies:
  contributor: contributors
  category: categories
  tag: tags

minify:
  tdewolff:
    html:
      keepWhitespace: false

related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
    - name: categories
      weight: 100
    - name: tags
      weight: 80
    - name: date
      weight: 10

module:
  hugoVersion:
    extended: true
    min: 0.80.0
    max: ''
  mounts:
    - source: assets
      target: assets
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: node_modules/flexsearch
      target: assets/js/vendor/flexsearch
    - source: node_modules/mermaid
      target: assets/js/vendor/mermaid
    - source: node_modules/@hyas/images/layouts
      target: layouts
