# Meta Data for SEO

## Homepage
title: Poke
titleSeparator: '-'
titleAddition: A simple and powerful tool for E2E-testing
description: >-
  Just imagine, that you can write E2E tests using familiar javascript syntax without any external dependencies,
  like node.js, jest, Axios, etc. Sounds like something impossible? 😉

## Open Graph
images: [poke.png]
ogLocale: en_US

## Twitter Cards
#schemaType: Person
schemaType: Organization
schemaName: Poke
schemaAuthor: tarampampam
schemaAuthorGitHub: 'https://github.com/tarampampam'
schemaLocale: en-US
schemaLogo: logo.png
schemaLogoWidth: 512
schemaLogoHeight: 512
schemaImage: poke.png
schemaImageWidth: 1280
schemaImageHeight: 640
schemaGitHub: 'https://github.com/tarampampam/poke'

## Sitelinks Search Box
siteLinksSearchBox: false

## Chrome Browser
themeColor: '#fff'

# Images
quality: 85
bgColor: '#fff'
landscapePhotoWidths: [900,800,700,600,500]
portraitPhotoWidths: [800,700,600,500]
lqipWidth: 20x
smallLimit: '300'

# Images
imageResponsive: true
imageConvertTo: webp
imageImageSizes: [480,720,1080,1280,1600,2048]
singleSize: false
imageAddClass: img-fluid lazyload blur-up

### Image template
defaultImage: default-image.png
fillImage: 1270x740 Center

# Footer
footer: >-
  Site generated with <a class="text-muted" href="https://gohugo.io/">Hugo</a> (<a
  class="text-muted" href="https://getdoks.org/" rel="nofollow">Doks</a> theme)

# Feed
#copyRight: Copyright (c) 2020-2021

# Alert
alert: false
alertDismissable: true
alertText: Alert text

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost: GitHub
#repoHost: Gitea
docsRepo: 'https://github.com/tarampampam/poke'
docsRepoBranch: master
docsRepoSubPath: 'docs'
editPage: true
lastMod: false

sections:
  sectionNav: [docs]

options:
  lazySizes: true
  clipBoard: true
  instantPage: true
  flexSearch: true
  searchSectionsShow: []
  searchSectionsIndex: []
  darkMode: true
  bootStrapJs: true
  breadCrumb: false
  highLight: true
  multilingualMode: false
  fullWidth: false
  navbarSticky: true
  toTopButton: false
  scrollSpy: false # experimental; needs Bootstrap >= 5.2.0-beta1

menu:
  section:
    auto: true
    collapsibleSidebar: false
